version: "3.9"

services:

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  posts-db:
    image: postgres:16
    container_name: posts-db
    environment:
      POSTGRES_DB: postsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - posts_postgres_data:/var/lib/postgresql/data


volumes:
  auth_postgres_data:
  posts_postgres_data: